networks:
  lv-network:

services:
  lv-postgres:
    container_name: lv-postgres
    image: postgres:16.1
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - lv-network
    volumes:
      - /mnt/${VOLUME_NAME}/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=localhost
      - TZ=America/Vancouver
      - PGTZ=America/Vancouver

  lv-adminer:
    container_name: lv-adminer
    image: adminer:4.8.1
    ports:
      - 3001:8080
    networks:
      - lv-network
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
    depends_on:
      - lv-postgres
