networks:
  lv-network:

services:
  lv-postgres:
    container_name: lv-postgres
    image: postgres:16.1
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - lv-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=localhost
      - TZ=America/Vancouver
      - PGTZ=America/Vancouver
