version: '3.8'

networks:
  lv-network:

services:
  lv-postgres:
    container_name: lv-postgres
    image: postgres:16.1
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - lv-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=localhost
      - TZ=America/Vancouver
      - PGTZ=America/Vancouver

  lv-s3-ninja:
    container_name: lv-s3-ninja
    image: scireum/s3-ninja:8.3.2
    ports:
      - 9444:9000
    networks:
      - lv-network
