version: '3.8'

networks:
  lv-network:

services:
  lv-server:
    container_name: lv-client
    image: ${IMAGE_NAME}
    ports:
      - 3000:3000
    networks:
      - lv-network
    environment:
      - VITE_ENVIRONMENT=${ENVIRONMENT}
      - VITE_DOMAIN=${DOMAIN}
      - VITE_AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - VITE_AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - VITE_CLIENT_ID=${CLIENT_ID}
      - VITE_REDIRECT_URI=${REDIRECT_URI}
    depends_on:
      - lv-postgres

  lv-postgres:
    container_name: lv-postgres
    image: postgres:16.1
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - lv-network
    volumes:
      - /mnt/${VOLUME_NAME}/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=localhost
      - TZ=America/Vancouver
      - PGTZ=America/Vancouver

  lv-adminer:
    container_name: lv-adminer
    image: adminer:4.8.1
    ports:
      - 3001:8080
    networks:
      - lv-network
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
    depends_on:
      - lv-postgres
