name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: actions/checkout@v2
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: pulotum/larminay-vault:${{ GITHUB_RUN_ID }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: pulotum/larminay-vault:infrastructure
    steps:
      - name: Deploy to remote server
        uses: actions/checkout@v2
        run: 
          - export RESET_DATABASE=true
          - export IMAGE_NAME=pulotum/larminay-vault:${{ GITHUB_RUN_ID }}
          - cd infrastructure
          - bash deploy.sh
