name: Deploy Infrastructure

on:
  push:
    branches:
      - infrastructure

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: testing

    container:
      image: pulotum/larminay-vault:infrastructure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run deploy.sh
        run: |
          cd infrastructure
          bash deploy.sh
